services:
  db:
    image: mysql
    container_name: orcamentos-sinapi
    environment:
      MYSQL_ROOT_USERNAME: ${ENV_ROOT_USERNAME:root}
      MYSQL_ROOT_PASSWORD: ${ENV_ROOT_PASSWORD:1234}
    ports:
      - "3308:3306"
    volumes:
      - branches_data:/var/lib/mysql

volumes:
  branches_data: