server:
  port: 8090

spring:
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3308/orcamentos_sinapi?createDatabaseIfNotExist=true
    username: root
    password: ${ENV_ROOT_PASSWORD} # Essa senha deve ser igual a variavel de ambiente ENV_ROOT_PASSWORD do docker-compose
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
